import kyoto from "@/assets/dest-kyoto.jpg";
import santorini from "@/assets/dest-santorini.jpg";
import bali from "@/assets/dest-bali.jpg";
import alps from "@/assets/dest-alps.jpg";
import lisbon from "@/assets/dest-lisbon.jpg";
import marrakech from "@/assets/dest-marrakech.jpg";
import auckland from "@/assets/dest-auckland.jpg";
import beijing from "@/assets/dest-beijing.jpg";
import brussels from "@/assets/dest-brussels.jpg";
import cairo from "@/assets/dest-cairo.jpg";
import melbourne from "@/assets/dest-melbourne.jpg";
import mumbai from "@/assets/dest-mumbai.jpg";
import nairobi from "@/assets/dest-nairobi.jpg";
import riodejaneiro from "@/assets/dest-riodejaneiro.jpg";
import toronto from "@/assets/dest-toronto.jpg";

export type Destination = {
  slug: string;
  name: string;
  country: string;
  image: string;
  tagline: string;
  dailyBudget: number;
  score: number;
  tags: string[];
  season: string;
  trending?: boolean;
  metrics: {
    weather: number;
    food: number;
    nightlife: number;
    safety: number;
    transport: number;
    shopping: number;
    family: number;
    adventure: number;
    internetMbps: number;
    visaDifficulty: number;
    hotelPrice: number;
    mealPrice: number;
  };
};

export const DESTINATIONS: Destination[] = [
  {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    image: kyoto,
    tagline: "Temples, tea houses and blossom-lined canals.",
    dailyBudget: 165,
    score: 94,
    tags: ["History", "Food", "Photography"],
    season: "Spring",
    trending: true,
    metrics: {
      weather: 82,
      food: 96,
      nightlife: 72,
      safety: 97,
      transport: 95,
      shopping: 84,
      family: 88,
      adventure: 68,
      internetMbps: 138,
      visaDifficulty: 20,
      hotelPrice: 148,
      mealPrice: 22,
    },
  },
  {
    slug: "santorini",
    name: "Santorini",
    country: "Greece",
    image: santorini,
    tagline: "Caldera sunsets, white villages and blue water.",
    dailyBudget: 210,
    score: 91,
    tags: ["Beaches", "Relaxation", "Photography"],
    season: "Summer",
    trending: true,
    metrics: {
      weather: 93,
      food: 88,
      nightlife: 80,
      safety: 90,
      transport: 68,
      shopping: 70,
      family: 74,
      adventure: 62,
      internetMbps: 74,
      visaDifficulty: 25,
      hotelPrice: 235,
      mealPrice: 32,
    },
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    image: bali,
    tagline: "Rice terraces, surf breaks and jungle waterfalls.",
    dailyBudget: 85,
    score: 89,
    tags: ["Beaches", "Adventure", "Relaxation"],
    season: "Year-round",
    metrics: {
      weather: 84,
      food: 86,
      nightlife: 82,
      safety: 76,
      transport: 58,
      shopping: 72,
      family: 78,
      adventure: 92,
      internetMbps: 42,
      visaDifficulty: 35,
      hotelPrice: 62,
      mealPrice: 9,
    },
  },
  {
    slug: "interlaken",
    name: "Interlaken",
    country: "Switzerland",
    image: alps,
    tagline: "Alpine lakes, cable cars and glacier air.",
    dailyBudget: 245,
    score: 92,
    tags: ["Mountains", "Adventure", "Photography"],
    season: "Summer",
    metrics: {
      weather: 74,
      food: 78,
      nightlife: 52,
      safety: 98,
      transport: 97,
      shopping: 66,
      family: 90,
      adventure: 97,
      internetMbps: 160,
      visaDifficulty: 30,
      hotelPrice: 268,
      mealPrice: 42,
    },
  },
  {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    image: lisbon,
    tagline: "Tiled streets, trams and Atlantic light.",
    dailyBudget: 120,
    score: 90,
    tags: ["Food", "History", "Nightlife"],
    season: "Autumn",
    trending: true,
    metrics: {
      weather: 88,
      food: 92,
      nightlife: 90,
      safety: 89,
      transport: 84,
      shopping: 78,
      family: 82,
      adventure: 70,
      internetMbps: 122,
      visaDifficulty: 25,
      hotelPrice: 112,
      mealPrice: 18,
    },
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    image: marrakech,
    tagline: "Souks, riads and desert doorways.",
    dailyBudget: 95,
    score: 87,
    tags: ["Shopping", "History", "Food"],
    season: "Winter",
    metrics: {
      weather: 80,
      food: 85,
      nightlife: 66,
      safety: 72,
      transport: 64,
      shopping: 95,
      family: 70,
      adventure: 84,
      internetMbps: 38,
      visaDifficulty: 30,
      hotelPrice: 78,
      mealPrice: 11,
    },
  },
  {
    slug: "auckland",
    name: "Auckland",
    country: "New Zealand",
    image: auckland,
    tagline: "Harbor views, volcanic parks and year-round festivals.",
    dailyBudget: 170,
    score: 88,
    tags: ["Outdoors", "City", "Food"],
    season: "Spring",
    metrics: {
      weather: 80,
      food: 90,
      nightlife: 78,
      safety: 90,
      transport: 92,
      shopping: 80,
      family: 88,
      adventure: 85,
      internetMbps: 110,
      visaDifficulty: 25,
      hotelPrice: 160,
      mealPrice: 24,
    },
  },
  {
    slug: "beijing",
    name: "Beijing",
    country: "China",
    image: beijing,
    tagline: "Palaces, street markets and ancient dynasty energy.",
    dailyBudget: 110,
    score: 86,
    tags: ["History", "Culture", "Food"],
    season: "Autumn",
    metrics: {
      weather: 76,
      food: 89,
      nightlife: 78,
      safety: 70,
      transport: 92,
      shopping: 85,
      family: 84,
      adventure: 65,
      internetMbps: 92,
      visaDifficulty: 68,
      hotelPrice: 90,
      mealPrice: 12,
    },
  },
  {
    slug: "brussels",
    name: "Brussels",
    country: "Belgium",
    image: brussels,
    tagline: "Chocolate lanes, Art Nouveau and grand squares.",
    dailyBudget: 155,
    score: 86,
    tags: ["Food", "History", "Nightlife"],
    season: "Spring",
    metrics: {
      weather: 72,
      food: 94,
      nightlife: 82,
      safety: 88,
      transport: 90,
      shopping: 84,
      family: 86,
      adventure: 60,
      internetMbps: 118,
      visaDifficulty: 20,
      hotelPrice: 145,
      mealPrice: 28,
    },
  },
  {
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    image: cairo,
    tagline: "Pyramids, Nile sunsets and bustling bazaars.",
    dailyBudget: 95,
    score: 82,
    tags: ["History", "Adventure", "Culture"],
    season: "Winter",
    metrics: {
      weather: 83,
      food: 81,
      nightlife: 68,
      safety: 64,
      transport: 72,
      shopping: 88,
      family: 76,
      adventure: 91,
      internetMbps: 55,
      visaDifficulty: 30,
      hotelPrice: 82,
      mealPrice: 10,
    },
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    country: "Australia",
    image: melbourne,
    tagline: "Laneways, coffee culture and coastal escapes.",
    dailyBudget: 180,
    score: 90,
    tags: ["Food", "Art", "Shopping"],
    season: "Autumn",
    trending: true,
    metrics: {
      weather: 78,
      food: 95,
      nightlife: 88,
      safety: 91,
      transport: 92,
      shopping: 87,
      family: 85,
      adventure: 72,
      internetMbps: 130,
      visaDifficulty: 30,
      hotelPrice: 175,
      mealPrice: 30,
    },
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    image: mumbai,
    tagline: "Markets, seaside promenades and cinematic energy.",
    dailyBudget: 65,
    score: 84,
    tags: ["Food", "Culture", "City"],
    season: "Winter",
    metrics: {
      weather: 85,
      food: 92,
      nightlife: 80,
      safety: 68,
      transport: 70,
      shopping: 86,
      family: 78,
      adventure: 81,
      internetMbps: 75,
      visaDifficulty: 35,
      hotelPrice: 58,
      mealPrice: 10,
    },
  },
  {
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    image: nairobi,
    tagline: "Savannah day trips, urban markets and modern lodges.",
    dailyBudget: 130,
    score: 85,
    tags: ["Safari", "Wildlife", "Culture"],
    season: "Summer",
    metrics: {
      weather: 78,
      food: 82,
      nightlife: 72,
      safety: 70,
      transport: 75,
      shopping: 78,
      family: 80,
      adventure: 91,
      internetMbps: 70,
      visaDifficulty: 40,
      hotelPrice: 120,
      mealPrice: 18,
    },
  },
  {
    slug: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    image: riodejaneiro,
    tagline: "Beaches, carnival energy and Sugarloaf sunsets.",
    dailyBudget: 140,
    score: 88,
    tags: ["Beaches", "Nightlife", "Photography"],
    season: "Summer",
    trending: true,
    metrics: {
      weather: 90,
      food: 86,
      nightlife: 92,
      safety: 65,
      transport: 78,
      shopping: 76,
      family: 80,
      adventure: 85,
      internetMbps: 72,
      visaDifficulty: 25,
      hotelPrice: 135,
      mealPrice: 17,
    },
  },
  {
    slug: "toronto",
    name: "Toronto",
    country: "Canada",
    image: toronto,
    tagline: "Skyscrapers, lakefront parks and multicultural dining.",
    dailyBudget: 150,
    score: 87,
    tags: ["City", "Food", "Culture"],
    season: "Summer",
    metrics: {
      weather: 78,
      food: 92,
      nightlife: 84,
      safety: 92,
      transport: 88,
      shopping: 82,
      family: 86,
      adventure: 70,
      internetMbps: 140,
      visaDifficulty: 20,
      hotelPrice: 160,
      mealPrice: 25,
    },
  },
];

export function findDestination(query: string): Destination {
  const q = query.trim().toLowerCase();
  return (
    DESTINATIONS.find((d) => q.includes(d.name.toLowerCase()) || q.includes(d.slug)) ??
    DESTINATIONS.find((d) => q.includes(d.country.toLowerCase())) ??
    DESTINATIONS[0]!
  );
}