/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'
import { Route as VirtualDayTripIdRouteImport } from './routes/virtual-day.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualDayTripIdRoute = VirtualDayTripIdRouteImport.update({
  id: '/virtual-day/$tripId',
  path: '/virtual-day/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/destinations': typeof DestinationsRoute
  '/simulate': typeof SimulateRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/virtual-day/$tripId': typeof VirtualDayTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/destinations': typeof DestinationsRoute
  '/simulate': typeof SimulateRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/virtual-day/$tripId': typeof VirtualDayTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/destinations': typeof DestinationsRoute
  '/simulate': typeof SimulateRoute
  '/trips': typeof TripsRoute
  '/api/chat': typeof ApiChatRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/virtual-day/$tripId': typeof VirtualDayTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/compare'
    | '/destinations'
    | '/simulate'
    | '/trips'
    | '/api/chat'
    | '/trip/$tripId'
    | '/virtual-day/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/compare'
    | '/destinations'
    | '/simulate'
    | '/trips'
    | '/api/chat'
    | '/trip/$tripId'
    | '/virtual-day/$tripId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/compare'
    | '/destinations'
    | '/simulate'
    | '/trips'
    | '/api/chat'
    | '/trip/$tripId'
    | '/virtual-day/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  DestinationsRoute: typeof DestinationsRoute
  SimulateRoute: typeof SimulateRoute
  TripsRoute: typeof TripsRoute
  ApiChatRoute: typeof ApiChatRoute
  TripTripIdRoute: typeof TripTripIdRoute
  VirtualDayTripIdRoute: typeof VirtualDayTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-day/$tripId': {
      id: '/virtual-day/$tripId'
      path: '/virtual-day/$tripId'
      fullPath: '/virtual-day/$tripId'
      preLoaderRoute: typeof VirtualDayTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  DestinationsRoute: DestinationsRoute,
  SimulateRoute: SimulateRoute,
  TripsRoute: TripsRoute,
  ApiChatRoute: ApiChatRoute,
  TripTripIdRoute: TripTripIdRoute,
  VirtualDayTripIdRoute: VirtualDayTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
